CREATE DATABASE FACULDADE
GO
USE FACULDADE

CREATE TABLE [PROJECTS](
[ID] INT NOT NULL IDENTITY(10001, 1),
[NAME] VARCHAR(100) NOT NULL,
[DESCRIPTION] VARCHAR(250) NULL,
[DATE] DATE NOT NULL CHECK([DATE] > '2014-09-01'),
PRIMARY KEY([ID])
)

CREATE TABLE [USERS](
[ID] INT NOT NULL IDENTITY,
[NAME] VARCHAR(100) NOT NULL,
[USERNAME] VARCHAR(45) NOT NULL UNIQUE,
[PASSWORD] VARCHAR(45) NOT NULL DEFAULT('123mudar'),
[EMAIL] VARCHAR(50) NOT NULL
PRIMARY KEY([ID])
)

CREATE TABLE [USERS HAS PROJECTS](
[USERS ID] INT NOT NULL,
[PROJECTS ID] INT NOT NULL
PRIMARY KEY ([USERS ID], [PROJECTS ID])
FOREIGN KEY ([USERS ID]) REFERENCES [USERS]([ID]),
FOREIGN KEY ([PROJECTS ID]) REFERENCES [PROJECTS]([ID])
)

ALTER TABLE [dbo].[USERS]
ALTER COLUMN [USERNAME] VARCHAR(10) NOT NULL

ALTER TABLE [dbo].[USERS]
ALTER COLUMN [PASSWORD] VARCHAR(08) NOT NULL

INSERT INTO [dbo].[USERS](
[NAME], [USERNAME], [PASSWORD], [EMAIL]
) VALUES(
'Maria', 'Rh_maria', ' ', 'maria@empresa.com',
'Paulo', 'Ti_paulo', '123@456', 'paulo@empresa.com',
'Ana', 'Rh_ana', ' ', 'ana@empresa.com',
'Clara', 'Ti_clara', ' ', 'clara@empresa.com',
'Aparecido', 'Rh_apareci', '55@!cido', 'aparecido@empresa.com'
)

INSERT INTO [dbo].[PROJECTS](
[NAME], [DESCRIPTION], [DATE]
) VALUES(
'Re‐folha', 'Refatoração das Folhas', '2014-09-05',
'Manutenção PC´s', 'Manutenção PC´s', '2014-09-06',
'Auditoria', NULL, '2014-09-07'
)

INSERT INTO [dbo].[USERS HAS PROJECTS](
[USERS ID], [PROJECTS ID]
) VALUES(
1, 10001,
5, 10001,
3, 10003,
4, 10002,
2, 10002
)

UPDATE [dbo].[PROJECTS]
SET [DATE] = '2014-09-12'
WHERE [ID] = 10002

UPDATE [dbo].[USERS]
SET [USERNAME] = 'Rh_cido'
WHERE [ID] = 5

UPDATE [dbo].[USERS]
SET [PASSWORD] = '888@*'
WHERE [USERNAME] = 'Rh_maria'

DELETE [dbo].[USERS HAS PROJECTS]
WHERE [USERS ID] = 2

ALTER TABLE [dbo].[PROJECTS]
ADD [BUDGET] DECIMAL(7,2) NULL

INSERT INTO [dbo].[PROJECTS](
[ID], [BUDGET]
) VALUES(
10001, 5750.00,
10002, 7850.00,
10003, 9530.00
)

SELECT [USERNAME], [PASSWORD] FROM [USERS]
WHERE [NAME] = 'Ana'

SELECT [NAME], [BUDGET]
	([BUDGET] * 1.25) AS [VALOR HIPOTETICO]
FROM [PROJECTS]

SELECT [ID], [NAME], [EMAIL]
FROM [USERS]
WHERE [PASSWORD] = '123mudar'

SELECT [ID], [NAME]
FROM [USERS]
WHERE [BUDGET] BETWEEN 2000.00 AND 8000.00
