CREATE DATABASE LIVRARIA_2
GO
USE [LIVRARIA_2]

CREATE TABLE [LIVRO](
[CODIGO LIVRO] INT NOT NULL IDENTITY(1001,1),
[NOME] VARCHAR(100) NOT NULL,
[LINGUA] VARCHAR(50) NOT NULL DEFAULT('PT-BR'),
[ANO] INT NOT NULL CHECK([ANO] < 1990),
PRIMARY KEY([CODIGO LIVRO])
)

CREATE TABLE [EDIÇOES](
[ISBN] INT NOT NULL,
[PREÇO] DECIMAL(7,2) NOT NULL CHECK([PREÇO] < 0.0),
[ANO] DATE NOT NULL CHECK([ANO] < '1993-01-01'),
[NUM PAGINAS] INT NOT NULL CHECK([NUM PAGINAS] < 0),
[QTD ESTOQUE] INT NOT NULL,
[LIVROCODIGO LIVRO] INT NOT NULL
PRIMARY KEY([ISBN])
FOREIGN KEY ([LIVROCODIGO LIVRO]) REFERENCES [LIVRO]([CODIGO LIVRO])
)

CREATE TABLE [AUTOR](
[CODIGO AUTOR] INT NOT NULL IDENTITY(10001,1),
[NOME] VARCHAR(100) NOT NULL UNIQUE,
[NASCIMENTO] DATE NOT NULL,
[PAIS] VARCHAR(50) NOT NULL,
[BIOGRAFIA] VARCHAR(MAX) NOT NULL,
PRIMARY KEY([CODIGO AUTOR])
)

CREATE TABLE [EDITORA](
[CODIGO EDITORA] INT NOT NULL,
[NOME] VARCHAR(50) NOT NULL UNIQUE,
[LOGRADOURO] VARCHAR(255) NOT NULL,
[NUMERO] INT NOT NULL CHECK([NUMERO] < 1),
[CEP] CHAR(08) NOT NULL,
[TELEFONE] CHAR(11) NOT NULL
PRIMARY KEY([CODIGO EDITORA])
)

CREATE TABLE [LIVRO AUTOR](
[LIVROCODIGO LIVRO] INT NOT NULL,
[AUTORCODIGO AUTOR] INT NOT NULL
PRIMARY KEY ([LIVROCODIGO LIVRO], [AUTORCODIGO AUTOR])
FOREIGN KEY ([LIVROCODIGO LIVRO]) REFERENCES [LIVRO]([CODIGO LIVRO]),
FOREIGN KEY ([AUTORCODIGO AUTOR]) REFERENCES [AUTOR]([CODIGO AUTOR])
)

CREATE TABLE [EDIÇOES EDITORA](
[EDIÇOESISBN] INT NOT NULL,
[EDITORACODIGO EDITORA] INT NOT NULL,
[LIVROCODIGO LIVRO] INT NOT NULL
PRIMARY KEY ([EDIÇOESISBN], [EDITORACODIGO EDITORA], [LIVROCODIGO LIVRO])
FOREIGN KEY ([EDIÇOESISBN]) REFERENCES [EDIÇOES]([ISBN]),
FOREIGN KEY ([EDITORACODIGO EDITORA]) REFERENCES [EDITORA]([CODIGO EDITORA]),
FOREIGN KEY ([LIVROCODIGO LIVRO]) REFERENCES [LIVRO]([CODIGO LIVRO])
)

/*ALTERANDO NOME DA COLUNA EM 'EDIÇOES'*/
EXEC sp_rename '[dbo].[EDIÇOES].[ANO]', '[ANOEDIÇOES]', 'COLUMN'

/*ALTERAR TIPO DO ATRIBUTO*/
ALTER TABLE [dbo].[EDITORA]
ALTER COLUMN [NOME] VARCHAR(30) NOT NULL

/*ALTERAR NOME E TIPO DA COLUNA*/
EXEC sp_rename '[dbo].[AUTOR].[NASCIMENTO]', '[ANO]', 'COLUMN'
ALTER TABLE [dbo].[AUTOR]
ALTER COLUMN [ANO] INT NOT NULL

/*POPULANDO 'LIVROS'*/
INSERT INTO [dbo].[LIVRO](
[NOME], [LINGUA], [ANO]
) VALUES(
'CCNA 4.1', '', 2015,
'HTML 5', '', 2017,
'Redes de Computadores', 'EN', 2010,
'Android em Ação', '', 2018
)

/*POPULANDO 'AUTOR'*/
INSERT INTO [dbo].[AUTOR](
[NOME], [NASCIMENTO], [PAIS], [BIOGRAFIA]
)VALUES(
'Inácio da Silva', '1975', 'BRASIL', 'Programador WEB desde 1995',
'Andrew Tannenbaum', '1944', 'EUA', 'Chefe do Departamento de Sistemas de Computação da Universidade de Vrij',
'Luis Rocha', '1967', 'BRASIL', 'Programador Mobile desde 2000',
'David Halliday', '1916', 'EUA', 'Físico PH.Ddesde 1941'
)

/*POPULANDO 'EDIÇOES'*/
INSERT INTO [dbo].[EDIÇOES](
[ISBN], [PREÇO], [ANO], [NUM PAGINAS], [QTD ESTOQUE]
)VALUES(
0130661023, 189.99, '2018', 653, 10
)

/*ATUALIZANDO DADO NA TABELA 'AUTOR'*/
UPDATE [dbo].[AUTOR]
SET [BIOGRAFIA] = 'Chefe do Departamento de Sistemas de Computação da Universidade de Vrije'
WHERE [CODIGO AUTOR] = 10002

/*ATUALIZANDO DADO NA TABELA 'EDIÇOES'*/
UPDATE [dbo].[EDIÇOES]
SET [QTD ESTOQUE] = 09
WHERE [ISBN] = 0130661023

/*APAGANDO DADO NA TABELA 'AUTOR'*/
DELETE [dbo].[AUTOR]
WHERE [CODIGO AUTOR] = 10004