CREATE DATABASE LIVRARIA
GO
USE LIVRARIA

CREATE TABLE [LIVRO](
[CODIGO LIVRO] INT NOT NULL,
[NOME] VARCHAR(100) NOT NULL,
[LINGUA] VARCHAR(50) NOT NULL DEFAULT('PT-BR'),
[ANO] DATE NOT NULL CHECK([ANO] < '1990-01-01'),
PRIMARY KEY([CODIGO LIVRO])
)

CREATE TABLE [EDIÇOES](
[ISBN] INT NOT NULL,
[PREÇO] FLOAT NOT NULL CHECK([PREÇO] < 0.0),
[ANO] DATE NOT NULL CHECK([ANO] < '1993-01-01'),
[NUM PAGINAS] INT NOT NULL CHECK([NUM PAGINAS] < 0),
[QTD ESTOQUE] INT NOT NULL,
[LIVROCODIGO LIVRO] INT NOT NULL
PRIMARY KEY([ISBN])
FOREIGN KEY ([LIVROCODIGO LIVRO]) REFERENCES [LIVRO]([CODIGO LIVRO])
)

CREATE TABLE [AUTOR](
[CODIGO AUTOR] INT NOT NULL UNIQUE,
[NOME] VARCHAR(100) NOT NULL,
[NASCIMENTO] DATE NOT NULL,
[PAIS] VARCHAR(50) NOT NULL CHECK(([PAIS] = 'BRASIL') OR ([PAIS] = 'ALEMANHA')),
[BIOGRAFIA] VARCHAR(250) NOT NULL,
PRIMARY KEY([CODIGO AUTOR])
)

CREATE TABLE [EDITORA](
[CODIGO EDITORA] INT NOT NULL,
[NOME] VARCHAR(100) NOT NULL UNIQUE,
[LOGRADOURO] VARCHAR(250) NOT NULL,
[NUMERO] INT NOT NULL CHECK([NUMERO] < 1),
[CEP] INT NOT NULL,
[TELEFONE] INT NOT NULL
PRIMARY KEY([CODIGO EDITORA])
)

CREATE TABLE [LIVRO AUTOR](
[LIVROCODIGO LIVRO] INT NOT NULL,
[AUTORCODIGO AUTOR] INT NOT NULL
PRIMARY KEY ([LIVROCODIGO LIVRO], [AUTORCODIGO AUTOR])
FOREIGN KEY ([LIVROCODIGO LIVRO]) REFERENCES [LIVRO]([CODIGO LIVRO]),
FOREIGN KEY ([AUTORCODIGO AUTOR]) REFERENCES [AUTOR]([CODIGO AUTOR])
)

CREATE TABLE [EDIÇOES EDITORA](
[EDIÇOESISBN] INT NOT NULL,
[EDITORACODIGO EDITORA] INT NOT NULL
PRIMARY KEY ([EDIÇOESISBN], [EDITORACODIGO EDITORA])
FOREIGN KEY ([EDIÇOESISBN]) REFERENCES [EDIÇOES]([ISBN]),
FOREIGN KEY ([EDITORACODIGO EDITORA]) REFERENCES [EDITORA]([CODIGO EDITORA])
)