CREATE DATABASE LOJA ELETRONICA
GO
USE [LOJA ELETRONICA]

CREATE TABLE [CLIENTE](

[RG] CHAR(9) NOT NULL,
[CPF] CHAR(11) NOT NULL,
[NOME] VARCHAR(60) NOT NULL,
[LOGRADOURO END] VARCHAR(90) NOT NULL,
[NUMERO END] INT NOT NULL,
PRIMARY KEY ([RG])
)

CREATE TABLE [PEDIDO](
[NOTA FISCAL] INT IDENTITY(1001,1),
[VALOR] DECIMAL(6,2) NOT NULL,
[DT] DATE NOT NULL,
[RG CLIENTE] CHAR(9) NOT NULL,
PRIMARY KEY ([NOTA FISCAL]),
FOREIGN KEY ([RG CLIENTE]) REFERENCES [CLIENTE] ([RG])
)

CREATE TABLE [MERCADORIA](
[CODIGO] INT IDENTITY(10,1),
[DESCRIÇAO] VARCHAR(40) NOT NULL,
[PREÇO] DECIMAL(6,2) NOT NULL,
[QUANTIDADE] INT NOT NULL,
[COD FORNECEDOR] INT NOT NULL,
PRIMARY KEY ([CODIGO]),
FOREIGN KEY ([COD FORNECEDOR]) REFERENCES [FORNECEDOR] ([CODIGO])
)

CREATE TABLE [FORNECEDOR](
[CODIGO] INT IDENTITY(1,1),
[NOME] VARCHAR(30) NOT NULL,
[LOGRADOURO END] VARCHAR(60) NOT NULL,
[TELEFONE] VARCHAR(11),
[CGC] VARCHAR(15),
[CIDADE] VARCHAR(40),
[TRANSPORTE] VARCHAR(10),
[PAIS] VARCHAR(30),
[MOEDA] VARCHAR(10)
PRIMARY KEY ([CODIGO])
)

INSERT INTO [CLIENTE] VALUES 
('29531844',	'34519878040',	'Luiz André',	'R. Astorga', '500'),
('13514996x',	'84984285630',	'Maria Luiza',	'R. Piauí', '174'),
('121985541',	'23354997310',	'Ana Barbara',	'Av. Jaceguai', '1141'),
('23987746x',	'43587669920',	'Marcos Alberto',	'R. Quinze', '22')

INSERT INTO [PEDIDO] VALUES 
(	'754',	CONVERT(DATE,'01/04/2018',103),	'121985541'),
(	'350',	CONVERT(DATE,'02/04/2018',103),	'121985541'),
(	'30',	CONVERT(DATE,'02/04/2018',103),	'29531844'),
(	'1500',	CONVERT(DATE,'03/04/2018',103),	'13514996x')

INSERT INTO [MERCADORIA] VALUES
('Mouse',	'24',	'30',	'1'),
('Teclado',	'50',	'20',	'1'),
('Cx. De Som',	'30',	'8',	'2'),
('Monitor17',	'350',	'4',	'3'),
('Notebook',	'1500',	'7',	'4')

INSERT INTO [FORNECEDOR] VALUES
('Clone'	,'Av. Nações Unidas, 12000',	'1141487000',NULL,		'São Paulo',NULL, NULL, NULL),			
('Logitech',	'28th Street, 100',	'1800145990'	,NULL,	NULL,	'Avião',	'EUA',	'US$'),
('LG',	'Rod. Castello Branco',	'0800664400',	'415997810/0001',	'Sorocaba',NULL, NULL, NULL),	
('PcChips',	'Ponte da Amizade', NULL,	NULL, NULL,	'Navio',	'Py',	'US$')


SELECT CAST([VALOR] * 0.10 AS DECIMAL(6,2)) AS valor_com_desconto FROM [PEDIDO] WHERE [NOTA FISCAL] = '1003'

SELECT CAST([VALOR] * 0.05 AS DECIMAL(6,2)) AS valor_com_desconto FROM [PEDIDO] WHERE [VALOR] > 700.00

SELECT [PREÇO] FROM [MERCADORIA] WHERE [QUANTIDADE] < 10

UPDATE [MERCADORIA] SET [PREÇO] = [PREÇO] * 1.20 WHERE [QUANTIDADE] < 10

SELECT [DT], [VALOR] FROM [PEDIDO] WHERE [RG CLIENTE] IN (
      SELECT [RG] FROM [CLIENTE] WHERE [NOME] LIKE 'Luiz%'
)

SELECT [CPF], [NOME], [LOGRADOURO END] AS endereço FROM [CLIENTE] WHERE [RG] IN (
     SELECT [RG CLIENTE] FROM [PEDIDO] WHERE [NOTA FISCAL] = '1004'
)

SELECT [PAIS], [TRANSPORTE] FROM [FORNECEDOR] WHERE [CODIGO] IN (
     SELECT [COD FORNECEDOR] FROM [MERCADORIA] WHERE [DESCRIÇAO] = 'Cx. De Som'
)

SELECT [DESCRIÇAO], [QUANTIDADE] FROM [MERCADORIA] WHERE [COD FORNECEDOR] IN (
     SELECT [CODIGO] FROM [FORNECEDOR] WHERE [NOME] = 'Clone'
)

SELECT [LOGRADOURO END], [TELEFONE] FROM [FORNECEDOR] WHERE [CODIGO] IN (
     SELECT [COD FORNECEDOR] FROM [MERCADORIA] WHERE [DESCRIÇAO] LIKE '%Monitor%'
)

SELECT [MOEDA] FROM [FORNECEDOR] WHERE [CODIGO] IN (
     SELECT [COD FORNECEDOR] FROM [MERCADORIA] WHERE [DESCRIÇAO] LIKE '%Notebook%'
)

SELECT DATEDIFF(MONTH, [DT], GETDATE()) AS dias_passados,
       CASE WHEN (DATEDIFF(MONTH, [DT], GETDATE()) > 6)
	           THEN
			           'atrasado'
			   ELSE
			           'em dia'
	    END AS statu
FROM pedido

SELECT DISTINCT [CLIENTE].[NOME] AS cliente, (SELECT COUNT([PEDIDO].[NOTA FISCAL] FROM [PEDIDO] WHERE [RG CLIENTE] = [RG]) FROM [CLIENTE], [PEDIDO]
WHERE [CLIENTE].[RG] = [PEDIDO].[RG CLIENTE]

SELECT [CLIENTE].[RG], [CLIENTE].[CPF], [CLIENTE].[NOME], [CLIENTE].[LOGRADOURO END] 
FROM [CLIENTE] LEFT OUTER JOIN [PEDIDO]
ON [CLIENTE].[RG] = [PEDIDO].[RG CLIENTE]
WHERE [PEDIDO].[RG CLIENTE] IS NULL

-------------------------------------------------------------------------------------------------------------------------------------------------------------

CREATE DATABASE SUPERMERCADO
GO
USE [SUPERMERCADO]

CREATE TABLE [CLIENTE](
[CODIGO] INT IDENTITY(1,1),
[NOME] VARCHAR(60) NOT NULL,
[LOGRADOURO END] VARCHAR(80) NOT NULL,
[NUM END] INT NOT NULL,
[TELEFONE] CHAR(8) NOT NULL,
[TELEFONE COMERCIAL] CHAR(8),
PRIMARY KEY ([CODIGO])
)

CREATE TABLE [MERCADORIA](
[CODIGO] INT IDENTITY(1001,1),
[NOME] VARCHAR(40) NOT NULL,
[CORREDOR] INT NOT NULL,
[TIPO] INT NOT NULL,
[VALOR] DECIMAL(7,2) NOT NULL,
PRIMARY KEY ([CODIGO]),
FOREIGN KEY ([CORREDOR]) REFERENCES [CORREDOR] ([CODIGO]),
FOREIGN KEY ([TIPO]) REFERENCES [TIPO DE MERCADORIA] ([CODIGO])
)

CREATE TABLE [CORREDOR](
[CODIGO] INT IDENTITY(101,1),
[TIPO] INT,
[NOME] VARCHAR(40),
PRIMARY KEY ([CODIGO]),
FOREIGN KEY ([TIPO]) REFERENCES [TIPO DE MERCADORIA] ([CODIGO])
)

CREATE TABLE [TIPO DE MERCADORIA](
[CODIGO] INT IDENTITY(10001,1),
[NOME] VARCHAR(40) NOT NULL,
PRIMARY KEY ([CODIGO])
)

CREATE TABLE [COMPRA](
[NOTA FISCAL] INT NOT NULL,
[CODIGO CLIENTE] INT NOT NULL,
[VALOR] DECIMAL(7,2) NOT NULL,
PRIMARY KEY ([NOTA FISCAL]),
FOREIGN KEY ([CODIGO CLIENTE]) REFERENCES [CLIENTE] ([CODIGO])
)

INSERT INTO [CLIENTE] VALUES 
('Luis Paulo',	'R. Xv de Novembro', '100',	'45657878', null),
('Maria Fernanda',	'R. Anhaia', '1098',	'27289098'	,'40040090'),
('Ana Claudia',	'Av. Voluntários da Pátria', '876',	'21346548', null),	
('Marcos Henrique',	'R. Pantojo', '76',	'51425890',	'30394540'),
('Emerson Souza',	'R. Pedro Álvares Cabral', '97',	'44236545',	'39389900'),
('Ricardo Santos',	'Trav. Hum', '10',	'98789878', null)	


SELECT * FROM [CLIENTE]

INSERT INTO [TIPO DE MERCADORIA] VALUES
('Pães'),
('Frios'),
('Bolacha'),
('Clorados'),
('Frutas'),
('Esponjas'),
('Massas'),
('Molhos')

SELECT * FROM [TIPO DE MERCADORIA]

INSERT INTO [COMPRA] VALUES
('1234',	'2',	'200'),
('2345'	,'4',	'156'),
('3456'	,'6',	'354'),
('4567'	,'3',	'19')

SELECT * FROM [COMPRA]

INSERT INTO [CORREDOR] VALUES
(	'10001',	'Padaria'),
(	'10002',	'Calçados'),
(	'10003',	'Biscoitos'),
(	'10004',	'Limpeza'),
(	NULL,	NULL),
(	NULL,	NULL),
(	'10007',	'Congelados')

SELECT * FROM [CORREDOR]

INSERT INTO [MERCADORIA] VALUES
(	'Pão de Forma',	'101',	'10001',	3.5),
(	'Presunto',	'101',	'10002',	2.0),
(	'Cream Cracker',	'103',	'10003',	4.5),
(	'Água Sanitária',	'104',	'10004',	6.5),
(	'Maçã',	'105',	'10005',	0.9),
(	'Palha de Aço',	'106',	'10006',	1.3),
(	'Lasanha',	'107',	'10007',	9.7)

SELECT * FROM [MERCADORIA]

SELECT ISNULL([VALOR], '0') AS valor
FROM [COMPRA] WHERE [CODIGO CLIENTE] IN (
     SELECT [CODIGO] FROM [CLIENTE] WHERE [NOME] = 'Luis Fernando'
)

SELECT ISNULL([VALOR], '0') AS valor
FROM [COMPRA] WHERE [CODIGO CLIENTE] IN (
     SELECT [CODIGO] FROM [CLIENTE] WHERE [NOME] = 'Marcos Henrique'
)

SELECT [CLIENTE].[LOGRADOURO END] + ', ' + CAST([CLIENTE].[NUMERO END] AS VARCHAR(50)) AS endereco_completo, [CLIENTE].[TELEFONE]
FROM [CLIENTE], [COMPRA]
WHERE [COMPRA].[CODIGO CLIENTE] = [CLIENTE].[CODIGO]
AND [COMPRA].[NOTA FISCAL] = '4567'

SELECT [VALOR] FROM [MERCADORIA] WHERE [TIPO]IN (
     SELECT [CODIGO] FROM [TIPO DE MERCADORIA] WHERE [NOME] = 'Pães'
)

SELECT [NOME] FROM [CORREDOR] WHERE [CODIGO] IN (
     SELECT [CORREDOR] FROM [MERCADORIA] WHERE [NOME] = '%Lasanha%'
)

SELECT [NOME] FROM [CORREDOR] WHERE [TIPO]IN (
     SELECT [CODIGO] FROM [TIPO DE MERCADORIA] WHERE [NOME] = 'Clorados'
)

--------------------------------------------------------------------------------------------------------------------------------------------

CREATE DATABASE FARMACIA
GO
USE [FARMÁCIA]

CREATE TABLE [CLIENTE](
[CPF] CHAR(11) NOT NULL,
[NOME] VARCHAR(50) NOT NULL,
[LOGRADOURO END] VARCHAR(70) NOT NULL,
[NUM END] INT NOT NULL,
[BAIRRO END] VARCHAR(30) NOT NULL,
[TELEFONE] CHAR(9) NOT NULL,
PRIMARY KEY ([CPF])
)

CREATE TABLE [VENDAS](
[NOTA FISCAL] INT NOT NULL,
[CPF CLIENTE] CHAR(11) NOT NULL,
[CODIGO MEDICAMENTO] INT NOT NULL,
[QUANTIDADE] INT NOT NULL,
[VALOR TOTAL] DECIMAL(7,2) NOT NULL,
[DT] DATE NOT NULL,
PRIMARY KEY ([NOTA FISCAL], [CPF CLIENTE], [CODIGO CLIENTE]),
FOREIGN KEY ([CPF CLIENTE]) REFERENCES [CLIENTE] ([CPF]),
FOREIGN KEY ([CODIGO MEDICAMENTO]) REFERENCES [MEDICAMENTO] ([CODIGO])
)

CREATE TABLE [MEDICAMENTO](
[CODIGO] INT IDENTITY(1,1),
[NOME] VARCHAR(90) NOT NULL,
[APRESENTAÇAO] VARCHAR(50) NOT NULL,
[UNIDADE DE CADASTRO] VARCHAR(20) NOT NULL,
[PREÇO] DECIMAL(5,3) NOT NULL,
PRIMARY KEY ([CODIGO])
)

INSERT INTO [MEDICAMENTO] VALUES
('Acetato de medroxiprogesterona',  	 '150 mg/ml',  	 'Ampola',  	'6.700'),
('Aciclovir',  	 '200mg/comp.', 	 'Comprimido',  	'0.280'),
('Ácido Acetilsalicílico',  	'500mg/comp.',  	 'Comprimido' , 	'0.035'),
('Ácido Acetilsalicílico',	 '100mg/comp.',  	 'Comprimido',  	'0.030'),
('Ácido Fólico',  	 '5mg/comp.',  	 'Comprimido',  	'0.054'),
('Albendazol',  	 '400mg/comp. mastigável',  	 'Comprimido',  	'0.560'),
('Alopurinol',  	 '100mg/comp.',  	 'Comprimido',  	'0.080'),
('Amiodarona',  	 '200mg/comp.',  	 'Comprimido',  	'0.200'),
('Amitriptilina(Cloridrato)',  	 '25mg/comp.', 	 'Comprimido',  '0.220'),
('Amoxicilina', 	 '500mg/cáps.',  	 'Cápsula',  	'0.190')

SELECT * FROM [MEDICAMENTO] 

INSERT INTO [CLIENTE] VALUES
('34390898700',	'Maria Zélia',	'Anhaia',	'65',	'Barra Funda',	'92103762'),
('21345986290',	'Roseli Silva',	'Xv. De Novembro',	'987',	'Centro',	'82198763'),
('86927981825',	'Carlos Campos',	'Voluntários da Pátria',	'1276',	'Santana',	'98172361'),
('31098120900',	'João Perdizes',	'Carlos de Campos',	'90',	'Pari',	'61982371')

SELECT * FROM [CLIENTE]

INSERT INTO [VENDA] VALUES
('31501',	'86927981825',	'10',	'3',	'0.57',	CONVERT(DATE,'01/11/2010',103)),
('31501',	'86927981825',	'2',	'10',	'2.8',	CONVERT(DATE,'01/11/2010',103)),
('31501',	'86927981825',	'5',	'30',	'1.05',	CONVERT(DATE,'01/11/2010',103)),
('31501',	'86927981825',	'8',	'30',	'6.6',	CONVERT(DATE,'01/11/2010',103)),
('31502',	'34390898700',	'8',	'15',	'3'	 ,   CONVERT(DATE,'01/11/2010',103)),
('31502',	'34390898700',	'2',	'10',	'2.8',   CONVERT(DATE,'01/11/2010',103)),
('31502',	'34390898700',	'9',	'10',	'2.2',   CONVERT(DATE,'01/11/2010',103)),
('31503',	'31098120900',	'1',	'20',	'134',   CONVERT(DATE,'02/11/2010',103))

SELECT * FROM [VENDA]

SELECT m.[NOME], m.[APRESENTAÇAO], m.[UNIDADE DE CADASTRO], m.[PREÇO]
FROM [MEDICAMENTO] m LEFT OUTER JOIN [VENDA] v
ON m.[CODIGO] = v.[CODIGO MEDICAMENTO]
WHERE v.[CODIGO MEDICAMENTO] IS NULL

SELECT c.[NOME] 
FROM [CLIENTE] c, [VENDA] v, [MEDICAMENTO] m
WHERE c.[CPF] = v.[CPF CLIENTE]
AND v.[CODIGO MEDICAMENTO] = m.[CODIGO]
AND m.[NOME] = 'Amiodarona'

SELECT c.[CPF], c.[LOGRADOURO END] + ', ' + CAST(c.[NUM END] AS VARCHAR(10)) + ' - ' + c.[BAIRRO END] AS endereco_completo, m.[NOME], m.[APRESENTAÇAO], m.[UNIDADE DE CADASTRO], m.[PREÇO], v.[QUANTIDADE], v.[VALOR TOTAL]
FROM [CLIENTE] c, [VENDA] v, [MEDICAMENTO] m
WHERE m.[CODIGO] = v.[CODIGO MEDICAMENTO]
AND v.[CPF CLIENTE] = c.[CPF]
AND c.[NOME] = 'Maria Zélia'

SELECT DISTINCT CONVERT(CHAR(10) , v.[DT], 103) 
FROM [VENDA] v, [CLIENTE] c
WHERE c.[CPF] = v.[CPF CLIENTE]
AND c.[NOME] = 'Carlos Campos'

UPDATE [MEDICAMENTO] SET [NOME] = 'Cloridrato de Amitriptilina' WHERE [NOME] = 'Amitriptilina(Cloridrato)'

SELECT [NOME] FROM [MEDICAMENTO]

